### ISSUE TITLE
I run this howtio-docker and get this console message repeatly

### ISSUE THREAD

**Issue by fthamura** [fabric8io/hawtio-docker#1]
I got this error message repeatly in howtio-docker

I just use this command "docker run -p 9282:8080 -it fabric8/hawtio"

any setting should I follow?

Caused by: java.lang.Exception: Could not deserialize server side exception: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@4cce166c; line: 1, column: 2]
    at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:24)
    at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:14)
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
    at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)

**Comment by jstrachan** [comment]
Incidentally, the fabric8 console now uses the fabric8/fabric8-console docker image:
https://registry.hub.docker.com/u/fabric8/fabric8-console/

which is created from this source: https://github.com/fabric8io/fabric8-console

we should update the readme to point folks at that location...

**Comment by jimternet** [comment]
@jstrachan  can we use console without fabric8?

**Comment by jstrachan** [comment]
@jimternet you can use hawtio wherever you like really; its lots of plugins you can plug and play to make whatever console you need: http://hawt.io/overview/index.html

what kind of console did you have in mind? FWIW the hawtio console is included in OpenShift if you're using docker; you then get to look inside any JVM packaged as a docker image
